using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Albion.Network.Interface
{
    /// <summary>
    /// Логика взаимодействия для TextEditorWindow.xaml
    /// </summary>
    public partial class TextEditorWindow : Window
    {
        public TextEditorWindow()
        {
            InitializeComponent();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            this.DialogResult = true;
        }
        public string MobList
        {
            get { return list.Text; }
        }

        private void Button_Click_1(object sender, RoutedEventArgs e)
        {
            list.Text +=
$"T5_MOB_ROAMING_AVALON_TREASURE_MINION_STANDARD\nT6_MOB_ROAMING_AVALON_TREASURE_MINION_STANDARD\nT7_MOB_ROAMING_AVALON_TREASURE_MINION_STANDARD\nT8_MOB_ROAMING_AVALON_TREASURE_MINION_STANDARD\nT5_MOB_ROAMING_AVALON_TREASURE_MINION_UNCOMMON\nT6_MOB_ROAMING_AVALON_TREASURE_MINION_UNCOMMON\nT7_MOB_ROAMING_AVALON_TREASURE_MINION_UNCOMMON\nT8_MOB_ROAMING_AVALON_TREASURE_MINION_UNCOMMON\nT5_MOB_ROAMING_AVALON_TREASURE_MINION_RARE\nT6_MOB_ROAMING_AVALON_TREASURE_MINION_RARE\nT7_MOB_ROAMING_AVALON_TREASURE_MINION_RARE\nT8_MOB_ROAMING_AVALON_TREASURE_MINION_RARE\nT5_MOB_ROAMING_AVALON_TREASURE_MINION_LEGENDARY\nT6_MOB_ROAMING_AVALON_TREASURE_MINION_LEGENDARY\nT7_MOB_ROAMING_AVALON_TREASURE_MINION_LEGENDARY\nT8_MOB_ROAMING_AVALON_TREASURE_MINION_LEGENDARY\nT2_MOB_EVENT_HALLOWEEN_CHEST\nT3_MOB_EVENT_HALLOWEEN_CHEST\nT4_MOB_EVENT_HALLOWEEN_CHEST\nT5_MOB_EVENT_HALLOWEEN_CHEST\nT6_MOB_EVENT_HALLOWEEN_CHEST\nT7_MOB_EVENT_HALLOWEEN_CHEST\nT8_MOB_EVENT_HALLOWEEN_CHEST\nT4_MOB_TN_FOREST_CHEST\nT5_MOB_TN_FOREST_CHEST\nT6_MOB_TN_FOREST_CHEST\nT7_MOB_TN_FOREST_CHEST\nT8_MOB_TN_FOREST_CHEST\nT4_MOB_ROAMING_FOREST_CHEST\nT4_MOB_ROAMING_HIGHLAND_CHEST\nT4_MOB_ROAMING_SWAMP_CHEST\nT4_MOB_ROAMING_MOUNTAIN_CHEST\nT4_MOB_ROAMING_STEPPE_CHEST\nT5_MOB_ROAMING_FOREST_CHEST\nT5_MOB_ROAMING_HIGHLAND_CHEST\nT5_MOB_ROAMING_SWAMP_CHEST\nT5_MOB_ROAMING_MOUNTAIN_CHEST\nT5_MOB_ROAMING_STEPPE_CHEST\nT6_MOB_ROAMING_FOREST_CHEST\nT6_MOB_ROAMING_HIGHLAND_CHEST\nT6_MOB_ROAMING_SWAMP_CHEST\nT6_MOB_ROAMING_MOUNTAIN_CHEST\nT6_MOB_ROAMING_STEPPE_CHEST\nT7_MOB_ROAMING_FOREST_CHEST\nT7_MOB_ROAMING_HIGHLAND_CHEST\nT7_MOB_ROAMING_SWAMP_CHEST\nT7_MOB_ROAMING_MOUNTAIN_CHEST\nT7_MOB_ROAMING_STEPPE_CHEST\nT8_MOB_ROAMING_FOREST_CHEST\nT8_MOB_ROAMING_HIGHLAND_CHEST\nT8_MOB_ROAMING_SWAMP_CHEST\nT8_MOB_ROAMING_MOUNTAIN_CHEST\nT8_MOB_ROAMING_STEPPE_CHEST\nT2_MOB_EVENT_WINTER_CHEST\nT3_MOB_EVENT_WINTER_CHEST\nT4_MOB_EVENT_WINTER_CHEST\nT5_MOB_EVENT_WINTER_CHEST\nT6_MOB_EVENT_WINTER_CHEST\nT7_MOB_EVENT_WINTER_CHEST\nT8_MOB_EVENT_WINTER_CHEST\nT2_MOB_EVENT_EASTER_CHEST\nT3_MOB_EVENT_EASTER_CHEST\nT4_MOB_EVENT_EASTER_CHEST\nT5_MOB_EVENT_EASTER_CHEST\nT6_MOB_EVENT_EASTER_CHEST\nT7_MOB_EVENT_EASTER_CHEST\nT8_MOB_EVENT_EASTER_CHEST\nT2_MOB_EVENT_HALLOWEEN_RESOURCE\nT3_MOB_EVENT_HALLOWEEN_RESOURCE\nT4_MOB_EVENT_HALLOWEEN_RESOURCE\nT5_MOB_EVENT_HALLOWEEN_RESOURCE\nT6_MOB_EVENT_HALLOWEEN_RESOURCE\nT2_MOB_EVENT_WINTER_RESOURCE\nT3_MOB_EVENT_WINTER_RESOURCE\nT4_MOB_EVENT_WINTER_RESOURCE\nT5_MOB_EVENT_WINTER_RESOURCE\nT6_MOB_EVENT_WINTER_RESOURCE\nT2_MOB_EVENT_EASTER_RESOURCE\nT3_MOB_EVENT_EASTER_RESOURCE\nT4_MOB_EVENT_EASTER_RESOURCE\nT5_MOB_EVENT_EASTER_RESOURCE\nT6_MOB_EVENT_EASTER_RESOURCE";
        }
    }
}
